// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdActorGraphic.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdActorGraphic::DialogEvtCmdActorGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogEvtCmdActorGraphic::DialogEvtCmdActorGraphic
    szGraphic_staticbox = new wxStaticBox(this, -1, _("Graphic"));
    szActor_staticbox = new wxStaticBox(this, -1, _("Actor"));
    const wxString *chActor_choices = NULL;
    chActor = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chActor_choices, 0);
    bmpGraphic = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER);
    chbTranslucent = new wxCheckBox(this, wxID_ANY, _("Translucent"));
    btnGraphic = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdActorGraphic::set_properties()
{
    // begin wxGlade: DialogEvtCmdActorGraphic::set_properties
    SetTitle(_("Change actor graphic"));
    chActor->SetMinSize(wxSize(100, -1));
    bmpGraphic->SetMinSize(wxSize(48, 64));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdActorGraphic::do_layout()
{
    // begin wxGlade: DialogEvtCmdActorGraphic::do_layout
    wxBoxSizer* szActorGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szGraphic = new wxStaticBoxSizer(szGraphic_staticbox, wxHORIZONTAL);
    wxBoxSizer* szOptions = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* szActor = new wxStaticBoxSizer(szActor_staticbox, wxHORIZONTAL);
    szActor->Add(chActor, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szActor, 1, wxLEFT|wxRIGHT|wxBOTTOM, 1);
    szGraphic->Add(bmpGraphic, 0, wxRIGHT, 1);
    szOptions->Add(chbTranslucent, 0, wxLEFT|wxBOTTOM, 1);
    szOptions->Add(btnGraphic, 0, wxLEFT|wxTOP|wxEXPAND, 1);
    szGraphic->Add(szOptions, 0, wxEXPAND, 0);
    szTop->Add(szGraphic, 0, wxLEFT|wxRIGHT|wxBOTTOM, 1);
    szActorGraphic->Add(szTop, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szActorGraphic->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szActorGraphic);
    szActorGraphic->Fit(this);
    Layout();
    // end wxGlade
}

