// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDFLASHCHARACTER_H
#define DIALOGEVTCMDFLASHCHARACTER_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdFlashCharacter: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdFlashCharacter::ids
    // end wxGlade

    DialogEvtCmdFlashCharacter(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdFlashCharacter::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdFlashCharacter::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szColor_staticbox;
    wxStaticBox* szSample_staticbox;
    wxStaticBox* szTarget_staticbox;
    wxChoice* chTarget;
    wxStaticBitmap* bmpSample;
    wxStaticText* stColorMin;
    wxStaticText* stColorMax;
    wxStaticText* stRed;
    wxSlider* slRed;
    wxSpinCtrl* spinRed;
    wxStaticText* stGreen;
    wxSlider* slGreen;
    wxSpinCtrl* spinGreen;
    wxStaticText* stBlue;
    wxSlider* slBlue;
    wxSpinCtrl* spinBlue;
    wxStaticText* stOpacity;
    wxSlider* slOpacity;
    wxSpinCtrl* spinOpacity;
    wxSpinCtrl* spinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancelBtnHel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDFLASHCHARACTER_H
