// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGDBSELECTANYGRAPHIC_H
#define DIALOGDBSELECTANYGRAPHIC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogDbSelectAnyGraphic: public wxDialog {
public:
    // begin wxGlade: DialogDbSelectAnyGraphic::ids
    // end wxGlade

    DialogDbSelectAnyGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogDbSelectAnyGraphic::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogDbSelectAnyGraphic::attributes
    wxListBox* listGraphic;
    wxStaticBitmap* bmpGraphic;
    wxButton* btnOK;
    wxButton* btnCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGDBSELECTANYGRAPHIC_H
