// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDHP_H
#define DIALOGEVTCMDHP_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdHP: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdHP::ids
    // end wxGlade

    DialogEvtCmdHP(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdHP::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdHP::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szOperand_staticbox;
    wxStaticBox* szTarget_staticbox;
    wxRadioButton* rbtnTargetParty;
    wxRadioButton* rbtnTargetFixed;
    wxChoice* chTargetFixed;
    wxRadioButton* rbtnTargetVariable;
    wxTextCtrl* tcTargetVariable;
    wxButton* btnTargetVariable;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnOperandConstant;
    wxSpinCtrl* spinOperandConstant;
    wxRadioButton* rbtnOperandVariable;
    wxTextCtrl* tcOperandVariable;
    wxButton* btnOperandVariable;
    wxCheckBox* chbAllowNoBattle;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDHP_H
