// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDFADEMUSIC_H
#define DIALOGEVTCMDFADEMUSIC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdFadeMusic: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdFadeMusic::ids
    // end wxGlade

    DialogEvtCmdFadeMusic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdFadeMusic::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdFadeMusic::attributes
    wxStaticBox* szTime_staticbox;
    wxSlider* slTime;
    wxStaticText* stTime0Seconds;
    wxStaticText* stTime5Seconds;
    wxStaticText* stTime10Seconds;
    wxStaticText* stTime15Seconds;
    wxStaticText* stTime20Seconds;
    wxButton* btnFade;
    wxButton* btnPlay;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDFADEMUSIC_H
