// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogDbSelectAnyGraphic.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogDbSelectAnyGraphic::DialogDbSelectAnyGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: DialogDbSelectAnyGraphic::DialogDbSelectAnyGraphic
    const wxString *listGraphic_choices = NULL;
    listGraphic = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, listGraphic_choices, 0);
    bmpGraphic = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogDbSelectAnyGraphic::set_properties()
{
    // begin wxGlade: DialogDbSelectAnyGraphic::set_properties
    SetTitle(_("Graphic of Type..."));
    bmpGraphic->SetMinSize(wxSize(480, 480));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogDbSelectAnyGraphic::do_layout()
{
    // begin wxGlade: DialogDbSelectAnyGraphic::do_layout
    wxBoxSizer* szSelectAnyGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szTop->Add(listGraphic, 1, wxALL|wxEXPAND, 1);
    szTop->Add(bmpGraphic, 0, wxALL, 1);
    szSelectAnyGraphic->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szSelectAnyGraphic->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szSelectAnyGraphic);
    szSelectAnyGraphic->Fit(this);
    Layout();
    // end wxGlade
}

