// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDFACEGRAPHIC_H
#define DIALOGEVTCMDFACEGRAPHIC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdFaceGraphic: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdFaceGraphic::ids
    // end wxGlade

    DialogEvtCmdFaceGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdFaceGraphic::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdFaceGraphic::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szFaceGraphic2_staticbox;
    wxStaticBitmap* bmpFaceGraphic;
    wxButton* btnSelect;
    wxButton* btnDelete;
    wxRadioBox* rbPosition;
    wxCheckBox* chbHorizontalMirror;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDFACEGRAPHIC_H
