// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDPICTURE_H
#define DIALOGEVTCMDPICTURE_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdPicture: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdPicture::ids
    // end wxGlade

    DialogEvtCmdPicture(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdPicture::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdPicture::attributes
    wxStaticBox* szAttributes_staticbox;
    wxStaticBox* szTrasparency_staticbox;
    wxStaticBox* szIntensity_staticbox;
    wxStaticBox* szPosition_staticbox;
    wxStaticBox* szPicture2_staticbox;
    wxStaticBox* szNumber_staticbox;
    wxSpinCtrl* spinNumber;
    wxTextCtrl* tcPicture;
    wxButton* btnPicture;
    wxRadioButton* rbtnSpecify;
    wxStaticText* stSpecifyX;
    wxSpinCtrl* spinSpecifyX;
    wxStaticText* stSpecifyY;
    wxSpinCtrl* spinSpecifyY;
    wxRadioButton* rbtnVariable;
    wxStaticText* stVariableX;
    wxTextCtrl* tcVariableX;
    wxButton* btnVariableX;
    wxStaticText* stVariableY;
    wxTextCtrl* tcVariableY;
    wxButton* btnVariableY;
    wxStaticLine* linePicture;
    wxCheckBox* chbScrollMapFix;
    wxSpinCtrl* spinIntensity;
    wxStaticText* stIntensity;
    wxSpinCtrl* spinTrasparency;
    wxStaticText* stTrasparency;
    wxRadioBox* rbTrasparentColor;
    wxTextCtrl* tcAttributes;
    wxButton* btnAttributes;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDPICTURE_H
