// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDMOVESCREEN_H
#define DIALOGEVTCMDMOVESCREEN_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdMoveScreen: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdMoveScreen::ids
    // end wxGlade

    DialogEvtCmdMoveScreen(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdMoveScreen::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdMoveScreen::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szSpeed_staticbox;
    wxStaticBox* szTiles_staticbox;
    wxStaticBox* szDirection_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnUp;
    wxRadioButton* rbtnLeft;
    wxRadioButton* rbtnRight;
    wxRadioButton* rbtnDown;
    wxSpinCtrl* spinTiles;
    wxChoice* chSpeed;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDMOVESCREEN_H
