// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdDamage.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdDamage::DialogEvtCmdDamage(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdDamage::DialogEvtCmdDamage
    szAttack_staticbox = new wxStaticBox(this, -1, _("Attack"));
    szDefense_staticbox = new wxStaticBox(this, -1, _("Defense influence"));
    szIntelligence_staticbox = new wxStaticBox(this, -1, _("Intelligence influence"));
    szAttack2_staticbox = new wxStaticBox(this, -1, _("Attack"));
    szVariable_staticbox = new wxStaticBox(this, -1, _("Variable"));
    szTarget_staticbox = new wxStaticBox(this, -1, _("Target"));
    rbtnTargetParty = new wxRadioButton(this, wxID_ANY, _("Whole group"));
    rbtnTargetFixed = new wxRadioButton(this, wxID_ANY, _("Fixed"));
    const wxString *chTargetFixed_choices = NULL;
    chTargetFixed = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chTargetFixed_choices, 0);
    rbtnTargetVariable = new wxRadioButton(this, wxID_ANY, _("Variable"));
    tcTargetVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnTargetVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    spinAttack = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    spinDefense = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stDefense = new wxStaticText(this, wxID_ANY, _("%"));
    spinIntelligence = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stInteligence = new wxStaticText(this, wxID_ANY, _("%"));
    spinAttack2 = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    chbVariableEnable = new wxCheckBox(this, wxID_ANY, _("Enable"));
    tcVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdDamage::set_properties()
{
    // begin wxGlade: DialogEvtCmdDamage::set_properties
    SetTitle(_("Take damage"));
    chTargetFixed->SetMinSize(wxSize(50, -1));
    tcTargetVariable->SetMinSize(wxSize(50, -1));
    spinAttack->SetMinSize(wxSize(50, -1));
    spinDefense->SetMinSize(wxSize(50, -1));
    spinIntelligence->SetMinSize(wxSize(50, -1));
    spinAttack2->SetMinSize(wxSize(50, -1));
    tcVariable->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdDamage::do_layout()
{
    // begin wxGlade: DialogEvtCmdDamage::do_layout
    wxBoxSizer* szDamage = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szMiddleBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szVariable = new wxStaticBoxSizer(szVariable_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szAttack2 = new wxStaticBoxSizer(szAttack2_staticbox, wxHORIZONTAL);
    wxBoxSizer* szMiddleTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szIntelligence = new wxStaticBoxSizer(szIntelligence_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szDefense = new wxStaticBoxSizer(szDefense_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szAttack = new wxStaticBoxSizer(szAttack_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szTarget = new wxStaticBoxSizer(szTarget_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* gszTarget = new wxFlexGridSizer(3, 2, 2, 2);
    wxBoxSizer* szTargetVariable = new wxBoxSizer(wxHORIZONTAL);
    gszTarget->Add(rbtnTargetParty, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    gszTarget->Add(0, 0, 1, wxEXPAND, 0);
    gszTarget->Add(rbtnTargetFixed, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    gszTarget->Add(chTargetFixed, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    gszTarget->Add(rbtnTargetVariable, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    szTargetVariable->Add(tcTargetVariable, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTargetVariable->Add(btnTargetVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszTarget->Add(szTargetVariable, 1, wxEXPAND, 0);
    gszTarget->AddGrowableCol(1);
    szTarget->Add(gszTarget, 1, wxEXPAND, 0);
    szDamage->Add(szTarget, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szAttack->Add(spinAttack, 1, wxALIGN_CENTER_VERTICAL, 0);
    szMiddleTop->Add(szAttack, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szDefense->Add(spinDefense, 1, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szDefense->Add(stDefense, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szMiddleTop->Add(szDefense, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szIntelligence->Add(spinIntelligence, 1, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szIntelligence->Add(stInteligence, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szMiddleTop->Add(szIntelligence, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szDamage->Add(szMiddleTop, 0, wxEXPAND, 0);
    szAttack2->Add(spinAttack2, 1, 0, 0);
    szMiddleBottom->Add(szAttack2, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szVariable->Add(chbVariableEnable, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szVariable->Add(tcVariable, 1, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szVariable->Add(btnVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    szMiddleBottom->Add(szVariable, 1, wxLEFT|wxRIGHT|wxBOTTOM, 1);
    szDamage->Add(szMiddleBottom, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szDamage->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szDamage);
    szDamage->Fit(this);
    Layout();
    // end wxGlade
}

