// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGMATERIAL_H
#define DIALOGMATERIAL_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogMaterial: public wxDialog {
public:
    // begin wxGlade: DialogMaterial::ids
    // end wxGlade

    DialogMaterial(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogMaterial::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogMaterial::attributes
    wxListBox* listFolders;
    wxListBox* listFiles;
    wxButton* btnImport;
    wxButton* btnExport;
    wxButton* btnDelete;
    wxRadioBox* rbFormat;
    wxButton* btnClose;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGMATERIAL_H
