// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdActorNameInput.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdActorNameInput::DialogEvtCmdActorNameInput(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogEvtCmdActorNameInput::DialogEvtCmdActorNameInput
    szOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    szActor_staticbox = new wxStaticBox(this, -1, _("Actor"));
    const wxString *chActor_choices = NULL;
    chActor = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chActor_choices, 0);
    const wxString rbMode_choices[] = {
        _("Hiragana"),
        _("Katakana")
    };
    rbMode = new wxRadioBox(this, wxID_ANY, _("Initial mode"), wxDefaultPosition, wxDefaultSize, 2, rbMode_choices, 1, wxRA_SPECIFY_ROWS);
    chbShowName = new wxCheckBox(this, wxID_ANY, _("Show initial name"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdActorNameInput::set_properties()
{
    // begin wxGlade: DialogEvtCmdActorNameInput::set_properties
    SetTitle(_("Actor name input"));
    chActor->SetMinSize(wxSize(100, -1));
    rbMode->SetSelection(0);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdActorNameInput::do_layout()
{
    // begin wxGlade: DialogEvtCmdActorNameInput::do_layout
    wxBoxSizer* szActorNameInput = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szActor = new wxStaticBoxSizer(szActor_staticbox, wxHORIZONTAL);
    szActor->Add(chActor, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szActor, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szTop->Add(rbMode, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szActorNameInput->Add(szTop, 0, wxEXPAND, 0);
    szOptions->Add(chbShowName, 1, 0, 0);
    szActorNameInput->Add(szOptions, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szActorNameInput->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szActorNameInput);
    szActorNameInput->Fit(this);
    Layout();
    // end wxGlade
}

