// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdInn.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdInn::DialogEvtCmdInn(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdInn::DialogEvtCmdInn
    szPrice_staticbox = new wxStaticBox(this, -1, _("Stay price"));
    SzOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    szMessage_staticbox = new wxStaticBox(this, -1, _("Inn message type"));
    const wxString *chMessage_choices = NULL;
    chMessage = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chMessage_choices, 0);
    spin_ctrl_1 = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    ChkCondition = new wxCheckBox(this, wxID_ANY, _("Create condition"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdInn::set_properties()
{
    // begin wxGlade: DialogEvtCmdInn::set_properties
    SetTitle(_("Visit inn"));
    chMessage->SetMinSize(wxSize(50, -1));
    spin_ctrl_1->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdInn::do_layout()
{
    // begin wxGlade: DialogEvtCmdInn::do_layout
    wxBoxSizer* szInn = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szMiddle = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* SzOptions = new wxStaticBoxSizer(SzOptions_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szPrice = new wxStaticBoxSizer(szPrice_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szMessage = new wxStaticBoxSizer(szMessage_staticbox, wxHORIZONTAL);
    szMessage->Add(chMessage, 1, wxALIGN_CENTER_VERTICAL, 0);
    szInn->Add(szMessage, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szPrice->Add(spin_ctrl_1, 1, wxALIGN_CENTER_VERTICAL, 0);
    szMiddle->Add(szPrice, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    SzOptions->Add(ChkCondition, 1, wxALIGN_CENTER_VERTICAL, 0);
    szMiddle->Add(SzOptions, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szInn->Add(szMiddle, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szInn->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szInn);
    szInn->Fit(this);
    Layout();
    // end wxGlade
}

