// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogDbMaxNumber.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogDbMaxNumber::DialogDbMaxNumber(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogDbMaxNumber::DialogDbMaxNumber
    stMaxNumber = new wxStaticText(this, wxID_ANY, _("Max number:"));
    spinMaxNumber = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 1, 5000);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogDbMaxNumber::set_properties()
{
    // begin wxGlade: DialogDbMaxNumber::set_properties
    SetTitle(_("Max number"));
    spinMaxNumber->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogDbMaxNumber::do_layout()
{
    // begin wxGlade: DialogDbMaxNumber::do_layout
    wxBoxSizer* szMaxNumber = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szTop->Add(stMaxNumber, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szTop->Add(spinMaxNumber, 1, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szMaxNumber->Add(szTop, 1, wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szMaxNumber->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szMaxNumber);
    szMaxNumber->Fit(this);
    Layout();
    // end wxGlade
}

