// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDGOTOMEMORIZEDPLACE_H
#define DIALOGEVTCMDGOTOMEMORIZEDPLACE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdGoToMemorizedPlace: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdGoToMemorizedPlace::ids
    // end wxGlade

    DialogEvtCmdGoToMemorizedPlace(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdGoToMemorizedPlace::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdGoToMemorizedPlace::attributes
    wxStaticBox* szVariable_staticbox;
    wxStaticText* stVariableMapID;
    wxTextCtrl* tcVariableMapID;
    wxButton* btnVariableMapID;
    wxStaticText* stVariableX;
    wxTextCtrl* tcVariableX;
    wxButton* btnVariableX;
    wxStaticText* stVariableY;
    wxTextCtrl* tcVariableY;
    wxButton* btnVariableY;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDGOTOMEMORIZEDPLACE_H
