// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdMessageOptions.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdMessageOptions::DialogEvtCmdMessageOptions(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdMessageOptions::DialogEvtCmdMessageOptions
    szOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    const wxString rbWindowType_choices[] = {
        _("Normal"),
        _("Transparent")
    };
    rbWindowType = new wxRadioBox(this, wxID_ANY, _("Window type"), wxDefaultPosition, wxDefaultSize, 2, rbWindowType_choices, 1, wxRA_SPECIFY_ROWS);
    const wxString rbWindowPosition_choices[] = {
        _("Top"),
        _("Center"),
        _("Bottom")
    };
    rbWindowPosition = new wxRadioBox(this, wxID_ANY, _("Window position"), wxDefaultPosition, wxDefaultSize, 3, rbWindowPosition_choices, 1, wxRA_SPECIFY_ROWS);
    chbDoNotCoverPlayer = new wxCheckBox(this, wxID_ANY, _("Don't cover player position by the window"));
    chbDoNotStopEvent = new wxCheckBox(this, wxID_ANY, _("Continue event execution while message is shown"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdMessageOptions::set_properties()
{
    // begin wxGlade: DialogEvtCmdMessageOptions::set_properties
    SetTitle(_("Message options"));
    rbWindowType->SetSelection(0);
    rbWindowPosition->SetSelection(2);
    chbDoNotCoverPlayer->SetValue(1);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdMessageOptions::do_layout()
{
    // begin wxGlade: DialogEvtCmdMessageOptions::do_layout
    wxBoxSizer* szMessageOptions = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxVERTICAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szTop->Add(rbWindowType, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szTop->Add(rbWindowPosition, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szMessageOptions->Add(szTop, 0, wxEXPAND, 0);
    szOptions->Add(chbDoNotCoverPlayer, 0, wxBOTTOM|wxEXPAND, 1);
    szOptions->Add(chbDoNotStopEvent, 0, wxTOP|wxEXPAND, 1);
    szMessageOptions->Add(szOptions, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szMessageOptions->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szMessageOptions);
    szMessageOptions->Fit(this);
    Layout();
    // end wxGlade
}

