// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDCALLEVENT_H
#define DIALOGEVTCMDCALLEVENT_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdCallEvent: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdCallEvent::ids
    // end wxGlade

    DialogEvtCmdCallEvent(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdCallEvent::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdCallEvent::attributes
    wxStaticBox* szEvent_staticbox;
    wxRadioButton* rbtnCommonEvent;
    wxChoice* chCommonEvent;
    wxRadioButton* rbtnMapEvent;
    wxChoice* chMapEvent;
    wxSpinCtrl* spinMapEvent;
    wxStaticText* stMapEvent;
    wxRadioButton* rbtnMapEventVariable;
    wxTextCtrl* tcMapEventVariableEvent;
    wxButton* btnMapEventVariableEvent;
    wxStaticText* stMapEventVariableEvent;
    wxTextCtrl* tcMapEventVariablePage;
    wxButton* btnMapEventVariablePage;
    wxStaticText* stMapEventVariablePage;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCALLEVENT_H
