// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDTELEPORT_H
#define DIALOGEVTCMDTELEPORT_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdTeleport: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTeleport::ids
    // end wxGlade

    DialogEvtCmdTeleport(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTeleport::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTeleport::attributes
    wxTreeCtrl* treeMaps;
    wxPanel* pnMap;
    wxStaticText* sTMap;
    wxToggleButton* btnScale11;
    wxToggleButton* btnScale12;
    wxToggleButton* btnScale14;
    wxButton* btnOK;
    wxButton* btnCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTELEPORT_H
