// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDTIMER_H
#define DIALOGEVTCMDTIMER_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdTimer: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTimer::ids
    // end wxGlade

    DialogEvtCmdTimer(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTimer::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTimer::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szOperation_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnSet;
    wxSpinCtrl* spinMinutes;
    wxStaticText* stMinutes;
    wxSpinCtrl* spinSeconds;
    wxStaticText* stSeconds;
    wxRadioButton* rbtnVariable;
    wxTextCtrl* tcVariable;
    wxButton* btnVariable;
    wxCheckBox* chbShowScreen;
    wxCheckBox* chbShowBattle;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTIMER_H
