// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdCallEvent.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdCallEvent::DialogEvtCmdCallEvent(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogEvtCmdCallEvent::DialogEvtCmdCallEvent
    szEvent_staticbox = new wxStaticBox(this, -1, _("Event to call"));
    rbtnCommonEvent = new wxRadioButton(this, wxID_ANY, _("Common event"));
    const wxString *chCommonEvent_choices = NULL;
    chCommonEvent = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chCommonEvent_choices, 0);
    rbtnMapEvent = new wxRadioButton(this, wxID_ANY, _("Map event"));
    const wxString *chMapEvent_choices = NULL;
    chMapEvent = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chMapEvent_choices, 0);
    spinMapEvent = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stMapEvent = new wxStaticText(this, wxID_ANY, _("page"));
    rbtnMapEventVariable = new wxRadioButton(this, wxID_ANY, _("Map event by variable"));
    tcMapEventVariableEvent = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnMapEventVariableEvent = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stMapEventVariableEvent = new wxStaticText(this, wxID_ANY, _("event to call"));
    tcMapEventVariablePage = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnMapEventVariablePage = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stMapEventVariablePage = new wxStaticText(this, wxID_ANY, _("page"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdCallEvent::set_properties()
{
    // begin wxGlade: DialogEvtCmdCallEvent::set_properties
    SetTitle(_("Call event"));
    chCommonEvent->SetMinSize(wxSize(50, -1));
    chMapEvent->SetMinSize(wxSize(50, -1));
    spinMapEvent->SetMinSize(wxSize(50, -1));
    tcMapEventVariableEvent->SetMinSize(wxSize(50, -1));
    tcMapEventVariablePage->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdCallEvent::do_layout()
{
    // begin wxGlade: DialogEvtCmdCallEvent::do_layout
    wxBoxSizer* szCallEvent = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szEvent = new wxStaticBoxSizer(szEvent_staticbox, wxVERTICAL);
    wxFlexGridSizer* gszMapEventVariable = new wxFlexGridSizer(2, 3, 2, 0);
    wxBoxSizer* szMapEvent = new wxBoxSizer(wxHORIZONTAL);
    szEvent->Add(rbtnCommonEvent, 0, wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 1);
    szEvent->Add(chCommonEvent, 0, wxTOP|wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 1);
    szEvent->Add(rbtnMapEvent, 0, wxTOP|wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 1);
    szMapEvent->Add(chMapEvent, 1, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szMapEvent->Add(spinMapEvent, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szMapEvent->Add(stMapEvent, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szEvent->Add(szMapEvent, 0, wxTOP|wxBOTTOM|wxEXPAND, 1);
    szEvent->Add(rbtnMapEventVariable, 0, wxTOP|wxBOTTOM|wxEXPAND|wxALIGN_CENTER_VERTICAL, 1);
    gszMapEventVariable->Add(tcMapEventVariableEvent, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    gszMapEventVariable->Add(btnMapEventVariableEvent, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    gszMapEventVariable->Add(stMapEventVariableEvent, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    gszMapEventVariable->Add(tcMapEventVariablePage, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    gszMapEventVariable->Add(btnMapEventVariablePage, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    gszMapEventVariable->Add(stMapEventVariablePage, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    gszMapEventVariable->AddGrowableCol(0);
    szEvent->Add(gszMapEventVariable, 1, wxTOP|wxEXPAND, 1);
    szCallEvent->Add(szEvent, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szCallEvent->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szCallEvent);
    szCallEvent->Fit(this);
    Layout();
    // end wxGlade
}

