// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDCOMMERCE_H
#define DIALOGEVTCMDCOMMERCE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdCommerce: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdCommerce::ids
    // end wxGlade

    DialogEvtCmdCommerce(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdCommerce::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdCommerce::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szObjects_staticbox;
    wxStaticBox* szStyle_staticbox;
    wxRadioBox* rbType;
    wxChoice* chStyle;
    wxListBox* listSell;
    wxButton* btnAdd;
    wxButton* btnRemove;
    wxListBox* listObjects;
    wxCheckBox* chbDoNotResell;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCOMMERCE_H
