// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDSYSTEMSOUND_H
#define DIALOGEVTCMDSYSTEMSOUND_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdSystemSound: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdSystemSound::ids
    // end wxGlade

    DialogEvtCmdSystemSound(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdSystemSound::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdSystemSound::attributes
    wxStaticBox* szSound_staticbox;
    wxStaticBox* SzSystemSound2_staticbox;
    wxChoice* chSystemSound;
    wxTextCtrl* tcSound;
    wxButton* btnSound;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDSYSTEMSOUND_H
