// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdMessage.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdMessage::DialogEvtCmdMessage(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdMessage::DialogEvtCmdMessage
    tcMessage = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_LINEWRAP|wxTE_WORDWRAP);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdMessage::set_properties()
{
    // begin wxGlade: DialogEvtCmdMessage::set_properties
    SetTitle(_("Show message"));
    tcMessage->SetMinSize(wxSize(523, 78));
    tcMessage->SetFont(wxFont(0, wxMODERN, wxNORMAL, wxNORMAL, 0, wxT("")));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdMessage::do_layout()
{
    // begin wxGlade: DialogEvtCmdMessage::do_layout
    wxBoxSizer* szMessage = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szMessage->Add(tcMessage, 1, wxALL|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szMessage->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szMessage);
    szMessage->Fit(this);
    Layout();
    // end wxGlade
}

