// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdFlashScreen.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdFlashScreen::DialogEvtCmdFlashScreen(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdFlashScreen::DialogEvtCmdFlashScreen
    szColor_staticbox = new wxStaticBox(this, -1, _("Flash color"));
    szTime_staticbox = new wxStaticBox(this, -1, _("Time"));
    szOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    szSample_staticbox = new wxStaticBox(this, -1, _("Sample"));
    bmpSample = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER);
    stMin = new wxStaticText(this, wxID_ANY, _("0"));
    stMax = new wxStaticText(this, wxID_ANY, _("31"));
    stRed = new wxStaticText(this, wxID_ANY, _("Red"));
    slRed = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinRed = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stGreen = new wxStaticText(this, wxID_ANY, _("Green"));
    slGreen = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinGreen = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stBlue = new wxStaticText(this, wxID_ANY, _("Blue"));
    slBlue = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinBlue = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stOpacity = new wxStaticText(this, wxID_ANY, _("Opacity"));
    slOpacity = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinOpacity = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    spinTime = new wxSpinCtrl(this, wxID_ANY, wxT("10"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stTime = new wxStaticText(this, wxID_ANY, _("x0.1 sec."));
    chbWait = new wxCheckBox(this, wxID_ANY, _("Wait to end"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdFlashScreen::set_properties()
{
    // begin wxGlade: DialogEvtCmdFlashScreen::set_properties
    SetTitle(_("Flash screen"));
    bmpSample->SetMinSize(wxSize(48, 64));
    spinRed->SetMinSize(wxSize(50, -1));
    spinGreen->SetMinSize(wxSize(50, -1));
    spinBlue->SetMinSize(wxSize(50, -1));
    spinOpacity->SetMinSize(wxSize(50, -1));
    spinTime->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdFlashScreen::do_layout()
{
    // begin wxGlade: DialogEvtCmdFlashScreen::do_layout
    wxBoxSizer* szFlashScreen = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szMiddle = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szTime = new wxStaticBoxSizer(szTime_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szColor = new wxStaticBoxSizer(szColor_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* szColorRight = new wxFlexGridSizer(5, 3, 2, 2);
    wxBoxSizer* SzColorRightTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szSample = new wxStaticBoxSizer(szSample_staticbox, wxHORIZONTAL);
    szSample->Add(bmpSample, 0, 0, 0);
    szColor->Add(szSample, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2);
    szColorRight->Add(0, 0, 0, wxEXPAND, 0);
    SzColorRightTop->Add(stMin, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    SzColorRightTop->Add(0, 0, 1, wxEXPAND, 0);
    SzColorRightTop->Add(stMax, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szColorRight->Add(SzColorRightTop, 1, wxEXPAND, 0);
    szColorRight->Add(0, 0, 0, wxEXPAND, 0);
    szColorRight->Add(stRed, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(slRed, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(spinRed, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stGreen, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(slGreen, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(spinGreen, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stBlue, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(slBlue, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(spinBlue, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stOpacity, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(slOpacity, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(spinOpacity, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->AddGrowableCol(1);
    szColor->Add(szColorRight, 1, 0, 0);
    szFlashScreen->Add(szColor, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szTime->Add(spinTime, 1, wxRIGHT|wxALIGN_CENTER_VERTICAL, 1);
    szTime->Add(stTime, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 1);
    szMiddle->Add(szTime, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szOptions->Add(chbWait, 1, wxALIGN_CENTER_VERTICAL, 0);
    szMiddle->Add(szOptions, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szFlashScreen->Add(szMiddle, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szFlashScreen->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szFlashScreen);
    szFlashScreen->Fit(this);
    Layout();
    // end wxGlade
}

