// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGMAP_H
#define DIALOGMAP_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/statline.h>
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogMap: public wxDialog {
public:
    // begin wxGlade: DialogMap::ids
    // end wxGlade

    DialogMap(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogMap::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogMap::attributes
    wxStaticBox* szBattleBackground_staticbox;
    wxStaticBox* szMapMusic_staticbox;
    wxStaticBox* szPanorama_staticbox;
    wxStaticBox* szParallaxOptions_staticbox;
    wxStaticBox* szPanoramaGraphic_staticbox;
    wxStaticBox* szTroopEncounters_staticbox;
    wxStaticBox* szLoopTime_staticbox;
    wxStaticBox* szSize_staticbox;
    wxStaticBox* szGraphics_staticbox;
    wxStaticBox* szName_staticbox;
    wxTextCtrl* tcName;
    wxChoice* chGraphics;
    wxSpinCtrl* spinSizeWidth;
    wxStaticText* stSize;
    wxSpinCtrl* spinSizeHeight;
    wxChoice* chLoopTime;
    wxListCtrl* lcTroopEncounters;
    wxStaticText* stEncounterSteps;
    wxSpinCtrl* spinEncounterSteps;
    wxCheckBox* chbUsePanorama;
    wxStaticBitmap* bmpPanoramaGraphic;
    wxButton* btnPanoramaGraphic;
    wxCheckBox* chbParallaxHorizontal;
    wxCheckBox* chbParallaxHorizontalAutomatic;
    wxStaticText* stParallaxHorizontalSpeed;
    wxSpinCtrl* spinParallaxHorizontalSpeed;
    wxStaticLine* szParallaxSeparator;
    wxCheckBox* chbParallaxVertical;
    wxCheckBox* chbParallaxVerticalAutomatic;
    wxStaticText* stParallaxVerticalSpeed;
    wxSpinCtrl* spinParallaxVerticalSpeed;
    wxRadioButton* rbtnMapMusicFromParentMap;
    wxRadioButton* rbtnMapMusicNone;
    wxRadioButton* rbtnMapMusicSelect;
    wxTextCtrl* tcMapMusicSelect;
    wxButton* btnMapMusicSelect;
    wxRadioButton* rbtnBattleBackgroundFromParentMap;
    wxRadioButton* rbtnBattleBackgroundFromTerrain;
    wxRadioButton* rbtnBattleBackgroundSelect;
    wxTextCtrl* tcBattleBackgroundSelect;
    wxButton* btnBattleBackgroundSelect;
    wxRadioBox* rbTeleport;
    wxRadioBox* rbEscape;
    wxRadioBox* rbSave;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGMAP_H
