// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDNUMBERINPUT_H
#define DIALOGEVTCMDNUMBERINPUT_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdNumberInput: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdNumberInput::ids
    // end wxGlade

    DialogEvtCmdNumberInput(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdNumberInput::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdNumberInput::attributes
    wxStaticBox* szVariable_staticbox;
    wxStaticBox* szFigures_staticbox;
    wxSpinCtrl* spinFigures;
    wxTextCtrl* tcVariable;
    wxButton* btnVariable;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDNUMBERINPUT_H
