// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDTELEPORTPLACE_H
#define DIALOGEVTCMDTELEPORTPLACE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdTeleportPlace: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTeleportPlace::ids
    // end wxGlade

    DialogEvtCmdTeleportPlace(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTeleportPlace::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTeleportPlace::attributes
    wxStaticBox* szSwitch_staticbox;
    wxStaticBox* szPosition_staticbox;
    wxRadioBox* rbOperation;
    wxTextCtrl* tcPosition;
    wxButton* btnPosition;
    wxCheckBox* chbSwitch;
    wxTextCtrl* tcSwitch;
    wxButton* btnSwitch;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTELEPORTPLACE_H
