// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdGetPositionID.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdGetPositionID::DialogEvtCmdGetPositionID(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdGetPositionID::DialogEvtCmdGetPositionID
    szPlace_staticbox = new wxStaticBox(this, -1, _("Place"));
    szStoreVariableID_staticbox = new wxStaticBox(this, -1, _("Store ID in variable"));
    szPlaceVariable_staticbox = new wxStaticBox(this, -1, _("Origin variable"));
    rbtnPlaceSpecify = new wxRadioButton(this, wxID_ANY, _("Specify"));
    tcPlaceSpecify = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPlaceSpecify = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    rbtnPlaceVariable = new wxRadioButton(this, wxID_ANY, _("Variable"));
    stPlaceVariableX = new wxStaticText(this, wxID_ANY, _("X ordinate:"));
    tcPlaceVariableX = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPlaceVariableX = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stPlaceVariableY = new wxStaticText(this, wxID_ANY, _("Y ordinate:"));
    tcPlaceVariableY = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPlaceVariableY = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    tcStoreVariableID = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnStoreVariableID = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdGetPositionID::set_properties()
{
    // begin wxGlade: DialogEvtCmdGetPositionID::set_properties
    SetTitle(_("Get position ID"));
    tcPlaceSpecify->SetMinSize(wxSize(50, -1));
    tcPlaceVariableX->SetMinSize(wxSize(50, -1));
    tcPlaceVariableY->SetMinSize(wxSize(50, -1));
    tcStoreVariableID->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdGetPositionID::do_layout()
{
    // begin wxGlade: DialogEvtCmdGetPositionID::do_layout
    wxBoxSizer* szGetPositionID = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szStoreVariableID = new wxStaticBoxSizer(szStoreVariableID_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szPlace = new wxStaticBoxSizer(szPlace_staticbox, wxVERTICAL);
    wxStaticBoxSizer* szPlaceVariable = new wxStaticBoxSizer(szPlaceVariable_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* gszPlaceVariable = new wxFlexGridSizer(2, 2, 2, 2);
    wxBoxSizer* szPlaceVariableY = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szPlaceVariableX = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szPlaceSpecify = new wxBoxSizer(wxHORIZONTAL);
    szPlaceSpecify->Add(rbtnPlaceSpecify, 0, wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szPlaceSpecify->Add(tcPlaceSpecify, 1, wxLEFT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szPlaceSpecify->Add(btnPlaceSpecify, 0, wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szPlace->Add(szPlaceSpecify, 0, wxEXPAND, 0);
    szPlace->Add(rbtnPlaceVariable, 0, wxTOP|wxEXPAND, 1);
    gszPlaceVariable->Add(stPlaceVariableX, 0, wxALIGN_CENTER_VERTICAL, 0);
    szPlaceVariableX->Add(tcPlaceVariableX, 1, wxALIGN_CENTER_VERTICAL, 0);
    szPlaceVariableX->Add(btnPlaceVariableX, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszPlaceVariable->Add(szPlaceVariableX, 1, wxEXPAND, 0);
    gszPlaceVariable->Add(stPlaceVariableY, 0, wxALIGN_CENTER_VERTICAL, 0);
    szPlaceVariableY->Add(tcPlaceVariableY, 1, wxALIGN_CENTER_VERTICAL, 0);
    szPlaceVariableY->Add(btnPlaceVariableY, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszPlaceVariable->Add(szPlaceVariableY, 1, wxEXPAND, 0);
    gszPlaceVariable->AddGrowableCol(1);
    szPlaceVariable->Add(gszPlaceVariable, 1, wxEXPAND, 0);
    szPlace->Add(szPlaceVariable, 0, wxEXPAND, 0);
    szGetPositionID->Add(szPlace, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szStoreVariableID->Add(tcStoreVariableID, 1, wxALIGN_CENTER_VERTICAL, 0);
    szStoreVariableID->Add(btnStoreVariableID, 0, wxALIGN_CENTER_VERTICAL, 0);
    szGetPositionID->Add(szStoreVariableID, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szGetPositionID->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szGetPositionID);
    szGetPositionID->Fit(this);
    Layout();
    // end wxGlade
}

