// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDSWAPEVENTS_H
#define DIALOGEVTCMDSWAPEVENTS_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdSwapEvents: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdSwapEvents::ids
    // end wxGlade

    DialogEvtCmdSwapEvents(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdSwapEvents::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdSwapEvents::attributes
    wxStaticBox* szEvent2_staticbox;
    wxStaticBox* szEvent1_staticbox;
    wxChoice* chEvent1;
    wxChoice* chEvent2;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDSWAPEVENTS_H
