// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDEVENTPOSITION_H
#define DIALOGEVTCMDEVENTPOSITION_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdEventPosition: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdEventPosition::ids
    // end wxGlade

    DialogEvtCmdEventPosition(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdEventPosition::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdEventPosition::attributes
    wxStaticBox* szPosition_staticbox;
    wxStaticBox* szPositionVariable_staticbox;
    wxStaticBox* szEvent_staticbox;
    wxChoice* chEvent;
    wxRadioButton* rbtnPositionEspecify;
    wxTextCtrl* tcPositionEspecify;
    wxButton* btnPositionEspecify;
    wxRadioButton* rbtnPositionVariable;
    wxStaticText* stPositionVariableX;
    wxTextCtrl* tcPositionVariableX;
    wxButton* btnPositionVariableX;
    wxStaticText* stPositionVariableY;
    wxTextCtrl* tcPositionVariableY;
    wxButton* btnPositionVariableY;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDEVENTPOSITION_H
