// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDPLAYVIDEO_H
#define DIALOGEVTCMDPLAYVIDEO_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdPlayVideo: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdPlayVideo::ids
    // end wxGlade

    DialogEvtCmdPlayVideo(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdPlayVideo::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdPlayVideo::attributes
    wxStaticBox* szPosition_staticbox;
    wxStaticBox* szSize_staticbox;
    wxStaticBox* szFile_staticbox;
    wxTextCtrl* stVideo;
    wxButton* btnVideo;
    wxSpinCtrl* spinSizeX;
    wxStaticText* stSize;
    wxSpinCtrl* spinSizeY;
    wxRadioButton* rbtnSpecify;
    wxStaticText* szSpecifyX;
    wxSpinCtrl* spinSpecifyX;
    wxStaticText* stSpecifyY;
    wxSpinCtrl* spinSpecifyY;
    wxRadioButton* rbtnVariable;
    wxStaticText* stVariableX;
    wxTextCtrl* tcVariableX;
    wxButton* btnVariableX;
    wxStaticText* stVariableY;
    wxTextCtrl* tcVariableY;
    wxButton* btnVariableY;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDPLAYVIDEO_H
