// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDMONEY_H
#define DIALOGEVTCMDMONEY_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdMoney: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdMoney::ids
    // end wxGlade

    DialogEvtCmdMoney(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdMoney::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdMoney::attributes
    wxStaticBox* SzOperandRight_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* RadioConstant;
    wxSpinCtrl* SpinConstant;
    wxRadioButton* RadioVar;
    wxTextCtrl* TextVar;
    wxButton* BtnVar;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDMONEY_H
