// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGDBMAXNUMBER_H
#define DIALOGDBMAXNUMBER_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogDbMaxNumber: public wxDialog {
public:
    // begin wxGlade: DialogDbMaxNumber::ids
    // end wxGlade

    DialogDbMaxNumber(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogDbMaxNumber::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogDbMaxNumber::attributes
    wxStaticText* stMaxNumber;
    wxSpinCtrl* spinMaxNumber;
    wxButton* btnOK;
    wxButton* btnCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGDBMAXNUMBER_H
