// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGDBLEARNSKILL_H
#define DIALOGDBLEARNSKILL_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogDbLearnSkill: public wxDialog {
public:
    // begin wxGlade: DialogDbLearnSkill::ids
    // end wxGlade

    DialogDbLearnSkill(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogDbLearnSkill::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogDbLearnSkill::attributes
    wxStaticBox* SzLevel_staticbox;
    wxStaticBox* szSkill_staticbox;
    wxChoice* chSkill;
    wxSpinCtrl* spinLevel;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGDBLEARNSKILL_H
