// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDMESSAGEOPTIONS_H
#define DIALOGEVTCMDMESSAGEOPTIONS_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdMessageOptions: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdMessageOptions::ids
    // end wxGlade

    DialogEvtCmdMessageOptions(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdMessageOptions::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdMessageOptions::attributes
    wxStaticBox* szOptions_staticbox;
    wxRadioBox* rbWindowType;
    wxRadioBox* rbWindowPosition;
    wxCheckBox* chbDoNotCoverPlayer;
    wxCheckBox* chbDoNotStopEvent;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDMESSAGEOPTIONS_H
