// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdVehicleGraphic.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdVehicleGraphic::DialogEvtCmdVehicleGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdVehicleGraphic::DialogEvtCmdVehicleGraphic
    szVehicle_staticbox = new wxStaticBox(this, -1, _("Vehicle graphic"));
    const wxString rbOperation_choices[] = {
        _("Small ship"),
        _("Big ship"),
        _("Aeroship")
    };
    rbOperation = new wxRadioBox(this, wxID_ANY, _("Operation"), wxDefaultPosition, wxDefaultSize, 3, rbOperation_choices, 1, wxRA_SPECIFY_COLS);
    bmpVehicle = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER);
    btnVehicle = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdVehicleGraphic::set_properties()
{
    // begin wxGlade: DialogEvtCmdVehicleGraphic::set_properties
    SetTitle(_("Change vehicle graphic"));
    rbOperation->SetSelection(0);
    bmpVehicle->SetMinSize(wxSize(48, 64));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdVehicleGraphic::do_layout()
{
    // begin wxGlade: DialogEvtCmdVehicleGraphic::do_layout
    wxBoxSizer* szVehicleGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szVehicle = new wxStaticBoxSizer(szVehicle_staticbox, wxHORIZONTAL);
    szTop->Add(rbOperation, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szVehicle->Add(bmpVehicle, 0, wxRIGHT, 1);
    szVehicle->Add(btnVehicle, 0, wxLEFT, 1);
    szTop->Add(szVehicle, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szVehicleGraphic->Add(szTop, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szVehicleGraphic->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szVehicleGraphic);
    szVehicleGraphic->Fit(this);
    Layout();
    // end wxGlade
}

