// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDMOVEPICTURE_H
#define DIALOGEVTCMDMOVEPICTURE_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdMovePicture: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdMovePicture::ids
    // end wxGlade

    DialogEvtCmdMovePicture(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdMovePicture::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdMovePicture::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szAttributes_staticbox;
    wxStaticBox* szTrasparency_staticbox;
    wxStaticBox* szIntensity_staticbox;
    wxStaticBox* szPicture_staticbox;
    wxStaticBox* szNumber_staticbox;
    wxSpinCtrl* spinNumber;
    wxRadioButton* rbtnSpecify;
    wxStaticText* stSpecifyX;
    wxSpinCtrl* spinSpecifyX;
    wxStaticText* stSpecifyY;
    wxSpinCtrl* spinSpecifyY;
    wxRadioButton* rbtnVariable;
    wxStaticText* stVariableX;
    wxTextCtrl* tcVariableX;
    wxButton* btnVariableX;
    wxStaticText* stVariableY;
    wxTextCtrl* tcVariableY;
    wxButton* btnVariableY;
    wxSpinCtrl* spinIntensity;
    wxStaticText* stIntensity;
    wxSpinCtrl* spinTrasparency;
    wxStaticText* stTrasparency;
    wxTextCtrl* tcAttributes;
    wxButton* btnAttributes;
    wxSpinCtrl* spinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDMOVEPICTURE_H
