// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdTransition.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdTransition::DialogEvtCmdTransition(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogEvtCmdTransition::DialogEvtCmdTransition
    szOut_staticbox = new wxStaticBox(this, -1, _("Out"));
    szIn_staticbox = new wxStaticBox(this, -1, _("In"));
    const wxString *chIn_choices = NULL;
    chIn = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chIn_choices, 0);
    const wxString *chOut_choices = NULL;
    chOut = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chOut_choices, 0);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTransition::set_properties()
{
    // begin wxGlade: DialogEvtCmdTransition::set_properties
    SetTitle(_("Change window transition"));
    chIn->SetMinSize(wxSize(50, -1));
    chOut->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTransition::do_layout()
{
    // begin wxGlade: DialogEvtCmdTransition::do_layout
    wxBoxSizer* szTransition = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOut = new wxStaticBoxSizer(szOut_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szIn = new wxStaticBoxSizer(szIn_staticbox, wxHORIZONTAL);
    szIn->Add(chIn, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szIn, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szOut->Add(chOut, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szOut, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szTransition->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szTransition->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szTransition);
    szTransition->Fit(this);
    Layout();
    // end wxGlade
}

