// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDSHAKE_H
#define DIALOGEVTCMDSHAKE_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdShake: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdShake::ids
    // end wxGlade

    DialogEvtCmdShake(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdShake::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdShake::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szSpeed_staticbox;
    wxStaticBox* szStrength_staticbox;
    wxSlider* slStrength;
    wxStaticText* stStrengthLower;
    wxStaticText* szStrengthNormal;
    wxStaticText* stStrengthHigher;
    wxSlider* slSpeed;
    wxStaticText* stSpeedSlower;
    wxStaticText* stSpeedNormal;
    wxStaticText* stSpeedFaster;
    wxSpinCtrl* spinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDSHAKE_H
