// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDCHOICE_H
#define DIALOGEVTCMDCHOICE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdChoice: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdChoice::ids
    // end wxGlade

    DialogEvtCmdChoice(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdChoice::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdChoice::attributes
    wxStaticBox* szOption4_staticbox;
    wxStaticBox* szOption3_staticbox;
    wxStaticBox* szOption2_staticbox;
    wxStaticBox* szOption1_staticbox;
    wxTextCtrl* tcOption1;
    wxTextCtrl* tcOption2;
    wxTextCtrl* tcOption3;
    wxTextCtrl* tcOption4;
    wxRadioBox* rbCancel;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCHOICE_H
