// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDVARIABLE_H
#define DIALOGEVTCMDVARIABLE_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdVariable: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdVariable::ids
    // end wxGlade

    DialogEvtCmdVariable(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdVariable::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdVariable::attributes
    wxStaticBox* szOperand_staticbox;
    wxStaticBox* szSwitch_staticbox;
    wxRadioButton* rbtnSet;
    wxTextCtrl* tcSwitchSet;
    wxButton* btnSwitchSet;
    wxRadioButton* rbtnoSwitchRange;
    wxSpinCtrl* spinSwitchRange1;
    wxStaticText* tcSwitchRange;
    wxSpinCtrl* spinSwitchRange2;
    wxRadioButton* rbtnSwitchVariable;
    wxTextCtrl* tcSwitchVariable;
    wxButton* btnSwitchVariable;
    wxStaticText* stSwitchVariable;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnOperandConstant;
    wxSpinCtrl* spinOperandConstant;
    wxRadioButton* rbtnOperandVariableA;
    wxTextCtrl* tcOperandVariableA;
    wxButton* btnOperandVariableA;
    wxRadioButton* rbtnOperandVariableB;
    wxTextCtrl* tcOperandVariableB;
    wxButton* btnOperandVariableB;
    wxStaticText* stOperandVarVaiableB;
    wxRadioButton* rbtnOperandRandom;
    wxSpinCtrl* spinOperandRandom1;
    wxSpinCtrl* spinOperandRandom2;
    wxRadioButton* rbtnOperandObject;
    wxChoice* chOperandObject;
    wxChoice* chOperandObject2;
    wxRadioButton* rbtnOperandActor;
    wxChoice* chOperandActor;
    wxChoice* chOperandActor2;
    wxRadioButton* rbtnOperandSprite;
    wxChoice* chOperandSprite;
    wxChoice* chOperandSprite2;
    wxRadioButton* rbtnOperandPut;
    wxChoice* chOperandPut;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDVARIABLE_H
