// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDITEM_H
#define DIALOGEVTCMDITEM_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdItem: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdItem::ids
    // end wxGlade

    DialogEvtCmdItem(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdItem::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdItem::attributes
    wxStaticBox* szOperand_staticbox;
    wxStaticBox* szObject_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnObjectFixed;
    wxChoice* chObjectFixed;
    wxRadioButton* rbtnObjectVariable;
    wxTextCtrl* tcObjectVariable;
    wxButton* btnObjectVariable;
    wxRadioButton* rbtnOperandConstant;
    wxSpinCtrl* spinOperandConstant;
    wxRadioButton* rbtnOperandVariable;
    wxTextCtrl* tcOperandVariable;
    wxButton* btnOperandVariable;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDITEM_H
