// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDPLAYSOUND_H
#define DIALOGEVTCMDPLAYSOUND_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdPlaySound: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdPlaySound::ids
    // end wxGlade

    DialogEvtCmdPlaySound(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdPlaySound::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdPlaySound::attributes
    wxStaticBox* szBalance_staticbox;
    wxStaticBox* szTempo_staticbox;
    wxStaticBox* szVolume_staticbox;
    wxStaticBox* szFadeIn_staticbox;
    wxListBox* listSound;
    wxSlider* slFadeIn;
    wxStaticText* stFadeInNone;
    wxStaticText* stFadeIn5Seconds;
    wxStaticText* stFadeIn10Seconds;
    wxSlider* slVolume;
    wxStaticText* stVolume0Percent;
    wxStaticText* stVolume50Percent;
    wxStaticText* stVolume100Percent;
    wxSlider* slTempo;
    wxStaticText* stTempo50Percent;
    wxStaticText* stTempo100Percent;
    wxStaticText* stTempo150Percent;
    wxSlider* slBalance;
    wxStaticText* stBalanceLeft;
    wxStaticText* stBalanceCenter;
    wxStaticText* stBalanceRight;
    wxButton* btnPlay;
    wxButton* btnStop;
    wxStaticLine* linePlayMusic;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDPLAYSOUND_H
