// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdSystemGraphic.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdSystemGraphic::DialogEvtCmdSystemGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX)
{
    // begin wxGlade: DialogEvtCmdSystemGraphic::DialogEvtCmdSystemGraphic
    const wxString *listSystem_choices = NULL;
    listSystem = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, listSystem_choices, 0);
    bmpSystem = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER);
    const wxString rbBackground_choices[] = {
        _("Expanded"),
        _("Tiled")
    };
    rbBackground = new wxRadioBox(this, wxID_ANY, _("Background"), wxDefaultPosition, wxDefaultSize, 2, rbBackground_choices, 1, wxRA_SPECIFY_COLS);
    const wxString rbFont_choices[] = {
        _("Gothic"),
        _("Modern")
    };
    rbFont = new wxRadioBox(this, wxID_ANY, _("Font"), wxDefaultPosition, wxDefaultSize, 2, rbFont_choices, 1, wxRA_SPECIFY_COLS);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdSystemGraphic::set_properties()
{
    // begin wxGlade: DialogEvtCmdSystemGraphic::set_properties
    SetTitle(_("Change system graphic"));
    bmpSystem->SetMinSize(wxSize(160, 80));
    rbBackground->SetSelection(0);
    rbFont->SetSelection(0);
    btnOK->SetDefault();
    btnHelp->SetDefault();
    // end wxGlade
}


void DialogEvtCmdSystemGraphic::do_layout()
{
    // begin wxGlade: DialogEvtCmdSystemGraphic::do_layout
    wxBoxSizer* szSystemGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szRight = new wxBoxSizer(wxVERTICAL);
    szTop->Add(listSystem, 1, wxALL|wxEXPAND, 1);
    szRight->Add(bmpSystem, 0, wxLEFT|wxRIGHT|wxTOP|wxALIGN_BOTTOM|wxALIGN_CENTER_HORIZONTAL, 1);
    szRight->Add(rbBackground, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szRight->Add(rbFont, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szTop->Add(szRight, 0, wxEXPAND, 0);
    szSystemGraphic->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szSystemGraphic->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szSystemGraphic);
    szSystemGraphic->Fit(this);
    Layout();
    // end wxGlade
}

