// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDTONE_H
#define DIALOGEVTCMDTONE_H

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdTone: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTone::ids
    // end wxGlade

    DialogEvtCmdTone(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTone::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTone::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szTone2_staticbox;
    wxStaticBox* szPreview_staticbox;
    wxStaticText* st0Percent;
    wxStaticText* st100Percent;
    wxStaticText* st200Percent;
    wxStaticText* stRed;
    wxSlider* slRed;
    wxSpinCtrl* spinRed;
    wxStaticText* stRedPercent;
    wxStaticText* stGreen;
    wxSlider* slGreen;
    wxSpinCtrl* spinGreen;
    wxStaticText* stGreenPercent;
    wxStaticText* stBlue;
    wxSlider* slBlue;
    wxSpinCtrl* spinBlue;
    wxStaticText* stBluePercent;
    wxStaticText* stSaturation;
    wxSlider* slSaturation;
    wxSpinCtrl* spinSaturation;
    wxStaticText* stSaturationPercent;
    wxStaticBitmap* bmpPreview;
    wxSpinCtrl* SpinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTONE_H
