// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdNumberInput.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdNumberInput::DialogEvtCmdNumberInput(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdNumberInput::DialogEvtCmdNumberInput
    szVariable_staticbox = new wxStaticBox(this, -1, _("Store value in variable"));
    szFigures_staticbox = new wxStaticBox(this, -1, _("Number of figures"));
    spinFigures = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    tcVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdNumberInput::set_properties()
{
    // begin wxGlade: DialogEvtCmdNumberInput::set_properties
    SetTitle(_("Show number input"));
    spinFigures->SetMinSize(wxSize(95, -1));
    tcVariable->SetMinSize(wxSize(125, -1));
    btnVariable->SetMinSize(wxSize(-1, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdNumberInput::do_layout()
{
    // begin wxGlade: DialogEvtCmdNumberInput::do_layout
    wxBoxSizer* szNumberInput = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szVariable = new wxStaticBoxSizer(szVariable_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szFigures = new wxStaticBoxSizer(szFigures_staticbox, wxHORIZONTAL);
    szFigures->Add(spinFigures, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szFigures, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szVariable->Add(tcVariable, 1, wxALIGN_CENTER_VERTICAL, 0);
    szVariable->Add(btnVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szVariable, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szNumberInput->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szNumberInput->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szNumberInput);
    szNumberInput->Fit(this);
    Layout();
    // end wxGlade
}

