// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdTileset.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdTileset::DialogEvtCmdTileset(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdTileset::DialogEvtCmdTileset
    szChipSet_staticbox = new wxStaticBox(this, -1, _("ChipSet"));
    const wxString *chChipSet_choices = NULL;
    chChipSet = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chChipSet_choices, 0);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTileset::set_properties()
{
    // begin wxGlade: DialogEvtCmdTileset::set_properties
    SetTitle(_("Change map tileset"));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTileset::do_layout()
{
    // begin wxGlade: DialogEvtCmdTileset::do_layout
    wxBoxSizer* szTileset = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szChipSet = new wxStaticBoxSizer(szChipSet_staticbox, wxHORIZONTAL);
    szChipSet->Add(chChipSet, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTileset->Add(szChipSet, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szTileset->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szTileset);
    szTileset->Fit(this);
    Layout();
    // end wxGlade
}

