// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDANIMATION_H
#define DIALOGEVTCMDANIMATION_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdAnimation: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdAnimation::ids
    // end wxGlade

    DialogEvtCmdAnimation(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdAnimation::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdAnimation::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTarget_staticbox;
    wxStaticBox* SzAnimation2_staticbox;
    wxStaticBitmap* bmpAnimation;
    wxChoice* chAnimation;
    wxChoice* chTarget;
    wxCheckBox* chbWait;
    wxCheckBox* chbWholeMapRange;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDANIMATION_H
