// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DIALOGEVTCMDBATTLE_H
#define DIALOGEVTCMDBATTLE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DialogEvtCmdBattle: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdBattle::ids
    // end wxGlade

    DialogEvtCmdBattle(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdBattle::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdBattle::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szBackground_staticbox;
    wxStaticBox* szTroop_staticbox;
    wxRadioButton* rbtnTroopFixed;
    wxChoice* chTroopFixed;
    wxRadioButton* rbtnTroopVariable;
    wxTextCtrl* tcTroopVariable;
    wxButton* btnTroopVariable;
    wxRadioButton* rbtnBackgroundFromTerrain;
    wxRadioButton* rbtnBackgroundSelect;
    wxTextCtrl* tcBackground;
    wxButton* btnBackground;
    wxRadioBox* rbEscape;
    wxRadioBox* rbDefeat;
    wxCheckBox* chbAlliedFirst;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDBATTLE_H
