// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdTimer.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdTimer::DialogEvtCmdTimer(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long WXUNUSED(style)):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdTimer::DialogEvtCmdTimer
    szOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    szOperation_staticbox = new wxStaticBox(this, -1, _("Operation"));
    const wxString rbOperation_choices[] = {
        _("Set value"),
        _("Start"),
        _("Stop")
    };
    rbOperation = new wxRadioBox(this, wxID_ANY, _("Operation"), wxDefaultPosition, wxDefaultSize, 3, rbOperation_choices, 1, wxRA_SPECIFY_ROWS);
    rbtnSet = new wxRadioButton(this, wxID_ANY, _("Set"));
    spinMinutes = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stMinutes = new wxStaticText(this, wxID_ANY, _("minutes"));
    spinSeconds = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stSeconds = new wxStaticText(this, wxID_ANY, _("seconds"));
    rbtnVariable = new wxRadioButton(this, wxID_ANY, _("By variable"));
    tcVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    chbShowScreen = new wxCheckBox(this, wxID_ANY, _("Show in screen"));
    chbShowBattle = new wxCheckBox(this, wxID_ANY, _("show in battle"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTimer::set_properties()
{
    // begin wxGlade: DialogEvtCmdTimer::set_properties
    SetTitle(_("Timer operations"));
    rbOperation->SetSelection(0);
    spinMinutes->SetMinSize(wxSize(50, -1));
    spinSeconds->SetMinSize(wxSize(50, -1));
    tcVariable->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTimer::do_layout()
{
    // begin wxGlade: DialogEvtCmdTimer::do_layout
    wxBoxSizer* szTimer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szOperation = new wxStaticBoxSizer(szOperation_staticbox, wxVERTICAL);
    wxBoxSizer* szVariable = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szSet = new wxBoxSizer(wxHORIZONTAL);
    szTimer->Add(rbOperation, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szSet->Add(rbtnSet, 0, wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szSet->Add(spinMinutes, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szSet->Add(stMinutes, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szSet->Add(spinSeconds, 1, wxLEFT|wxRIGHT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szSet->Add(stSeconds, 0, wxLEFT|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 1);
    szOperation->Add(szSet, 1, wxEXPAND, 0);
    szVariable->Add(rbtnVariable, 0, wxRIGHT|wxTOP|wxALIGN_CENTER_VERTICAL, 1);
    szVariable->Add(tcVariable, 1, wxLEFT|wxTOP|wxALIGN_CENTER_VERTICAL, 1);
    szVariable->Add(btnVariable, 0, wxTOP|wxALIGN_CENTER_VERTICAL, 1);
    szOperation->Add(szVariable, 1, wxEXPAND, 0);
    szTimer->Add(szOperation, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szOptions->Add(chbShowScreen, 1, wxRIGHT, 0);
    szOptions->Add(chbShowBattle, 1, wxLEFT, 0);
    szTimer->Add(szOptions, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnCancel, 0, wxALL|wxALIGN_BOTTOM, 1);
    szBottom->Add(btnHelp, 0, wxALL|wxALIGN_BOTTOM, 1);
    szTimer->Add(szBottom, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szTimer);
    szTimer->Fit(this);
    Layout();
    // end wxGlade
}

