// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include "DialogEvtCmdCommerce.h"

// begin wxGlade: ::extracode

// end wxGlade


DialogEvtCmdCommerce::DialogEvtCmdCommerce(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxTHICK_FRAME)
{
    // begin wxGlade: DialogEvtCmdCommerce::DialogEvtCmdCommerce
    szObjects_staticbox = new wxStaticBox(this, -1, _("Objects to sell"));
    szOptions_staticbox = new wxStaticBox(this, -1, _("Options"));
    szStyle_staticbox = new wxStaticBox(this, -1, _("Commerce style"));
    const wxString rbType_choices[] = {
        _("Normal"),
        _("Doesn't sell"),
        _("Doesn't buy")
    };
    rbType = new wxRadioBox(this, wxID_ANY, _("Commerce type"), wxDefaultPosition, wxDefaultSize, 3, rbType_choices, 1, wxRA_SPECIFY_ROWS);
    const wxString *chStyle_choices = NULL;
    chStyle = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, chStyle_choices, 0);
    const wxString *listSell_choices = NULL;
    listSell = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, listSell_choices, 0);
    btnAdd = new wxButton(this, wxID_ANY, _("< Add"), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnRemove = new wxButton(this, wxID_ANY, _("Remove >"), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    const wxString *listObjects_choices = NULL;
    listObjects = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, listObjects_choices, 0);
    chbDoNotResell = new wxCheckBox(this, wxID_ANY, _("Merchant doesn't sell goods already sold"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdCommerce::set_properties()
{
    // begin wxGlade: DialogEvtCmdCommerce::set_properties
    SetTitle(_("Visit commerce"));
    rbType->SetSelection(0);
    chStyle->SetMinSize(wxSize(50, -1));
    listSell->SetMinSize(wxSize(50, -1));
    listObjects->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdCommerce::do_layout()
{
    // begin wxGlade: DialogEvtCmdCommerce::do_layout
    wxBoxSizer* szCommerce = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    wxStaticBoxSizer* szObjects = new wxStaticBoxSizer(szObjects_staticbox, wxHORIZONTAL);
    wxBoxSizer* szAddRemove = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* szStyle = new wxStaticBoxSizer(szStyle_staticbox, wxHORIZONTAL);
    szCommerce->Add(rbType, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szStyle->Add(chStyle, 1, 0, 0);
    szCommerce->Add(szStyle, 0, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szObjects->Add(listSell, 1, wxRIGHT|wxEXPAND, 1);
    szAddRemove->Add(0, 0, 1, wxEXPAND, 0);
    szAddRemove->Add(btnAdd, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szAddRemove->Add(btnRemove, 0, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 1);
    szAddRemove->Add(0, 0, 1, wxEXPAND, 0);
    szObjects->Add(szAddRemove, 0, wxEXPAND, 0);
    szObjects->Add(listObjects, 1, wxLEFT|wxEXPAND, 1);
    szCommerce->Add(szObjects, 1, wxLEFT|wxRIGHT|wxEXPAND, 1);
    szOptions->Add(chbDoNotResell, 1, 0, 0);
    szCommerce->Add(szOptions, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szCommerce->Add(szBottom, 0, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 3);
    SetSizer(szCommerce);
    szCommerce->Fit(this);
    Layout();
    // end wxGlade
}

