/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Editor.
//
// EasyRPG Editor is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Editor is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Editor. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGABOUT_H_
#define _DLGABOUT_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgAbout_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_editor.h"

/// Implementing dlgAbout_Base
class dlgAbout : public dlgAbout_Base {
public:
	/// Constructor
	dlgAbout(wxWindow* parent);
private:
	/// Show credits window
	void btnCredits_click(wxCommandEvent& WXUNUSED(event));
	/// Close dialog on click
	void btnClose_click(wxCommandEvent& WXUNUSED(event));
};

#endif
