/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Editor.
//
// EasyRPG Editor is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Editor is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Editor. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGDB_H_
#define _DLGDB_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgDb_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_database.h"

/// Implementing dlgMap_Base
class dlgDb : public dlgDb_Base {
public:
	/// Constructor
	dlgDb(wxWindow* parent);
private:
	/// Show music dialog on click
	void btnMusic_click(wxCommandEvent& WXUNUSED(event));
	/// Accept dialog on click
	void btnOK_click(wxCommandEvent& WXUNUSED(event));
	/// Cancel dialog on click
	void btnCancel_click(wxCommandEvent& WXUNUSED(event));
};

// TODO:
// There are some undocumented keyboard actions in rm2k database:
// F4 / F5 should change between database listbox elements
// Ctrl+tab / Ctrl+Shift+tab should change between tabs

#endif
