/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Player.
//
// EasyRPG Player is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Player is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGEVT_H_
#define _DLGEVT_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgEvt_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_events.h"

/// Implementing dlgEvt_Base
class dlgEvt : public dlgEvt_Base {
public:
	/// Constructor
	dlgEvt(wxWindow* parent);
protected:
	/// Double click on event command list
	void EvtCmd_dclick(wxMouseEvent& WXUNUSED(event));
};

#endif
