/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Player.
//
// EasyRPG Player is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Player is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGEVTCMD_H_
#define _DLGEVTCMD_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgEvtCmd_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_events.h"

/// Implementing dlgEvtCmd_Base
class dlgEvtCmd : public dlgEvtCmd_Base {
public:
	/// Constructor
	dlgEvtCmd(wxWindow* parent);
private:
	void btnMessage_click(wxCommandEvent& WXUNUSED(event));
	void btnMessageOptions_click(wxCommandEvent& WXUNUSED(event));
	void btnFaceGraphic_click(wxCommandEvent& WXUNUSED(event));
	void btnChoice_click(wxCommandEvent& WXUNUSED(event));
	void btnNumberInput_click(wxCommandEvent& WXUNUSED(event));
	void btnSwitch_click(wxCommandEvent& WXUNUSED(event));
	void btnVariable_click(wxCommandEvent& WXUNUSED(event));
	void btnTimer_click(wxCommandEvent& WXUNUSED(event));
	void btnMoney_click(wxCommandEvent& WXUNUSED(event));
	void btnItem_click(wxCommandEvent& WXUNUSED(event));
	void btnParty_click(wxCommandEvent& WXUNUSED(event));
	void btnExperience_click(wxCommandEvent& WXUNUSED(event));
	void btnLevel_click(wxCommandEvent& WXUNUSED(event));
	void btnParameter_click(wxCommandEvent& WXUNUSED(event));
	void btnSkill_click(wxCommandEvent& WXUNUSED(event));
	void btnEquipment_click(wxCommandEvent& WXUNUSED(event));
	void btnHP_click(wxCommandEvent& WXUNUSED(event));
	void btnMP_click(wxCommandEvent& WXUNUSED(event));
	void btnState_click(wxCommandEvent& WXUNUSED(event));
	void btnRecover_click(wxCommandEvent& WXUNUSED(event));
	void btnDamage_click(wxCommandEvent& WXUNUSED(event));
	void btnActorName_click(wxCommandEvent& WXUNUSED(event));
	void btnActorTitle_click(wxCommandEvent& WXUNUSED(event));
	void btnActorGraphic_click(wxCommandEvent& WXUNUSED(event));
	void btnActorFaceGraphic_click(wxCommandEvent& WXUNUSED(event));
	void btnVehicleGraphic_click(wxCommandEvent& WXUNUSED(event));
	void btnSystemMusic_click(wxCommandEvent& WXUNUSED(event));
	void btnSystemSound_click(wxCommandEvent& WXUNUSED(event));
	void btnSystemGraphic_click(wxCommandEvent& WXUNUSED(event));
	void btnTransition_click(wxCommandEvent& WXUNUSED(event));
	
	void btnBattle_click(wxCommandEvent& WXUNUSED(event));
	void btnCommerce_click(wxCommandEvent& WXUNUSED(event));
	void btnInn_click(wxCommandEvent& WXUNUSED(event));
	void btnActorNameInput_click(wxCommandEvent& WXUNUSED(event));
	void btnTeleport_click(wxCommandEvent& WXUNUSED(event));
	void btnMemorizePlace_click(wxCommandEvent& WXUNUSED(event));
	void btnGoToMemorizedPlace_click(wxCommandEvent& WXUNUSED(event));
	void btnVehiclePosition_click(wxCommandEvent& WXUNUSED(event));
	void btnEventPosition_click(wxCommandEvent& WXUNUSED(event));
	void btnSwapEvents_click(wxCommandEvent& WXUNUSED(event));
	void btnGetTerrainID_click(wxCommandEvent& WXUNUSED(event));
	void btnGetPositionID_click(wxCommandEvent& WXUNUSED(event));
	void btnBlankScreen_click(wxCommandEvent& WXUNUSED(event));
	void btnShowScreen_click(wxCommandEvent& WXUNUSED(event));
	void btnTone_click(wxCommandEvent& WXUNUSED(event));
	void btnFlashScreen_click(wxCommandEvent& WXUNUSED(event));
	void btnShake_click(wxCommandEvent& WXUNUSED(event));
	void btnMoveScreen_click(wxCommandEvent& WXUNUSED(event));
	void btnWeather_click(wxCommandEvent& WXUNUSED(event));
	void btnPicture_click(wxCommandEvent& WXUNUSED(event));
	void btnMovePicture_click(wxCommandEvent& WXUNUSED(event));
	void btnDeletePicture_click(wxCommandEvent& WXUNUSED(event));
	void btnAnimation_click(wxCommandEvent& WXUNUSED(event));
	void btnActorTransparency_click(wxCommandEvent& WXUNUSED(event));
	void btnFlashCharacter_click(wxCommandEvent& WXUNUSED(event));
	void btnEventMovement_click(wxCommandEvent& WXUNUSED(event));
	void btnWait_click(wxCommandEvent& WXUNUSED(event));
	
	void btnPlayMusic_click(wxCommandEvent& WXUNUSED(event));
	void btnFadeMusic_click(wxCommandEvent& WXUNUSED(event));
	void btnPlaySound_click(wxCommandEvent& WXUNUSED(event));
	void btnPlayVideo_click(wxCommandEvent& WXUNUSED(event));
	void btnKeyAssignment_click(wxCommandEvent& WXUNUSED(event));
	void btnTileset_click(wxCommandEvent& WXUNUSED(event));
	void btnPanorama_click(wxCommandEvent& WXUNUSED(event));
	void btnEncounterRate_click(wxCommandEvent& WXUNUSED(event));
	void btnTile_click(wxCommandEvent& WXUNUSED(event));
	void btnTeleportPlace_click(wxCommandEvent& WXUNUSED(event));
	void btnTeleportPermissions_click(wxCommandEvent& WXUNUSED(event));
	void btnEscapePlace_click(wxCommandEvent& WXUNUSED(event));
	void btnEscapePermissions_click(wxCommandEvent& WXUNUSED(event));
	void btnSavePermissions_click(wxCommandEvent& WXUNUSED(event));
	void btnSystemMenuPermissions_click(wxCommandEvent& WXUNUSED(event));
	void btnConditions_click(wxCommandEvent& WXUNUSED(event));
	void btnLabel_click(wxCommandEvent& WXUNUSED(event));
	void btnGoToLabel_click(wxCommandEvent& WXUNUSED(event));
	void btnCallEvent_click(wxCommandEvent& WXUNUSED(event));
	void btnNote_click(wxCommandEvent& WXUNUSED(event));
	
	/// Closes dialog on click
	void Close_click(wxCommandEvent& WXUNUSED(event));
};

#endif
