/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Player.
//
// EasyRPG Player is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Player is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGEVTCMDFLASHSCREEN_H_
#define _DLGEVTCMDFLASHSCREEN_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgEvtCmdFlashScreen_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_events_page_2.h"

/// Implementing dlgEvtCmdFlashScreen_Base
class dlgEvtCmdFlashScreen : public dlgEvtCmdFlashScreen_Base {
public:
	/// Constructor
	dlgEvtCmdFlashScreen(wxWindow* parent);
private:
	/// Closes dialog on click
	void btnClose_click(wxCommandEvent& WXUNUSED(event));
};

#endif
