/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Editor.
//
// EasyRPG Editor is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Editor is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Editor. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _DLGOPEN_H_
#define _DLGOPEN_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of dlgOpen_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_editor.h"

/// Implementing dlgOpen_Base
class dlgOpen : public dlgOpen_Base {
public:
	/// Constructor
	dlgOpen(wxWindow* parent);
private:
	/// Show rename project window
	void btnRename_click(wxCommandEvent& WXUNUSED(event));
	/// Show delete message box
	void btnDelete_click(wxCommandEvent& WXUNUSED(event));
	/// Show select path window if space key is pressed from text control
	void tcPath_key(wxKeyEvent& WXUNUSED(event));
	/// Show select path window from text control double click
	void tcPath_dclick(wxMouseEvent& WXUNUSED(event));
	/// Show select path window from button click
	void btnPath_click(wxCommandEvent& WXUNUSED(event));
	/// Cancel dialog on click
	void btnCancel_click(wxCommandEvent& WXUNUSED(event));
	///Show select path window
	void SelectPath();
	///Refresh project list control
	void RefreshProjectList();
	/// Project base path
	wxString ProjectBasePath;
};

#endif
