// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRAMEEDITOR_H
#define FRAMEEDITOR_H

// begin wxGlade: ::dependencies
#include <wx/splitter.h>
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class FrameEditor: public wxFrame {
public:
    // begin wxGlade: FrameEditor::ids
    // end wxGlade

    FrameEditor(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: FrameEditor::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: FrameEditor::attributes
    wxMenuBar* frmEditorMenubar;
    wxStatusBar* frmEditorStatusbar;
    wxToolBar* frmEditorToolbar;
    wxScrolledWindow* pnEditorTileset;
    wxTreeCtrl* tcMapTree;
    wxPanel* pnEditorMapTree;
    wxSplitterWindow* swEditor;
    wxScrolledWindow* pnEditorMap;
    // end wxGlade
}; // wxGlade: end class


#endif // FRAMEEDITOR_H
