// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 15 04:53:05 2009 from "/home/fdelapena/programacion/easyrpg/trunk/editor/wxglade/easyrpg.wxg"

#include <wx/wx.h>
#include <wx/image.h>
#include "FrameEditor.h"



class AppEditor: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(AppEditor)

bool AppEditor::OnInit()
{
    wxInitAllImageHandlers();
    FrameEditor* frmEditor = new FrameEditor(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frmEditor);
    frmEditor->Show();
    return true;
}
