/////////////////////////////////////////////////////////////////////////////
// This file is part of EasyRPG Player.
//
// EasyRPG Player is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EasyRPG Player is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
/////////////////////////////////////////////////////////////////////////////

#ifndef _PNSYSTEM_H_
#define _PNSYSTEM_H_

////////////////////////////////////////////////////////////
/// @file
/// Subclass of pnSystem_Base, which is generated by wxFormBuilder.
////////////////////////////////////////////////////////////

#include "gui_database_system.h"

/// Implementing pnSystem_Base
class pnSystem : public pnSystem_Base {
public:
	/// Constructor
	pnSystem(wxWindow* parent);
};

#endif
